# Generated by Django 3.2.7 on 2021-09-20 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('pin', models.CharField(max_length=14, verbose_name='ПИН')),
                ('birthdate', models.DateField(verbose_name='Дата рождения')),
                ('phone', models.CharField(max_length=10, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Главрач',
                'verbose_name_plural': 'Главрачи',
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('region', models.CharField(choices=[('Osh', 'Ошская'), ('Chui', 'Чуйская'), ('IK', 'Иссык-Кульская'), ('Talas', 'Таласская'), ('Naryn', 'Нарынская'), ('Batken', 'Баткенская')], default='Osh', max_length=9, verbose_name='Область')),
                ('ocpo', models.CharField(max_length=4, unique=True, verbose_name='ОКПО')),
                ('gov', models.BooleanField(default=False, verbose_name='Государственное')),
                ('maxn', models.IntegerField(default=100, verbose_name='Макс.количество сотрудников')),
                ('doctors', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='main.maindoctor', verbose_name='Главрач')),
            ],
            options={
                'verbose_name': 'Больница',
                'verbose_name_plural': 'Больницы',
            },
        ),
    ]
