# Generated by Django 3.2.7 on 2021-09-24 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210921_1002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'Лечащий врач', 'verbose_name_plural': 'Лечащие врачи'},
        ),
        migrations.AlterField(
            model_name='patients',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='counts', to='main.doctor', verbose_name='Лечащий врач'),
        ),
    ]
